import json
import os
from datetime import datetime, timezone
from stix2 import AttackPattern, Bundle, Indicator, Relationship, ThreatActor


def _technique_to_attack_pattern(technique: dict):
    tid = technique.get("id", "T0000")
    return AttackPattern(
        name=technique.get("name", tid),
        description=technique.get("description", f"Observed ATT&CK technique {tid}"),
        external_references=[{"source_name": "mitre-attack", "external_id": tid}],
        allow_custom=True,
    )


def build_bundle(session_id: str, description: str, techniques: list, iocs: list, output_dir: str):
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%fZ")
    actor = ThreatActor(
        name="Unknown OT Threat Actor",
        description=description or "Behavioral profile generated by Shadow-OT",
        created=now,
        modified=now,
    )

    patterns = [_technique_to_attack_pattern(t) for t in techniques]
    indicators = []
    for ioc in iocs:
        value = ioc.get("value", "unknown")
        pattern = f"[x-shadowot-observable:value = '{value}']"
        indicators.append(Indicator(
            name=ioc.get("type", "ioc"),
            pattern_type="stix",
            pattern=pattern,
            valid_from=now,
            created=now,
            modified=now,
            allow_custom=True,
        ))

    rels = []
    for ap in patterns:
        rels.append(Relationship(source_ref=actor.id, target_ref=ap.id, relationship_type="uses", created=now, modified=now))
    for ap in patterns:
        for ind in indicators:
            rels.append(Relationship(source_ref=ap.id, target_ref=ind.id, relationship_type="indicates", created=now, modified=now))

    bundle = Bundle(objects=[actor, *patterns, *indicators, *rels], allow_custom=True)
    os.makedirs(output_dir, exist_ok=True)
    out_path = os.path.join(output_dir, f"bundle_{session_id}.json")
    with open(out_path, "w", encoding="utf-8") as handle:
        handle.write(bundle.serialize(pretty=True))
    return out_path
