import os
from datetime import datetime, timezone
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.platypus import Table, TableStyle


def _severity_color(severity: str):
    severity = (severity or "LOW").upper()
    if severity == "HIGH":
        return colors.HexColor("#B91C1C")
    if severity == "MEDIUM":
        return colors.HexColor("#D97706")
    return colors.HexColor("#15803D")


def _draw_page_title(c: canvas.Canvas, title: str):
    c.setFont("Helvetica-Bold", 20)
    c.drawString(24 * mm, 270 * mm, title)


def _draw_cover(c: canvas.Canvas, incident: dict):
    _draw_page_title(c, "SHADOW-OT INCIDENT REPORT")
    c.setFont("Helvetica", 12)
    c.drawString(24 * mm, 250 * mm, f"Session ID: {incident['session_id']}")
    c.drawString(24 * mm, 242 * mm, "Classification: CONFIDENTIAL")
    c.drawString(24 * mm, 234 * mm, f"Generated: {incident['timestamp']}")
    c.drawString(24 * mm, 226 * mm, "Generated by: Shadow-OT Automated Response Engine")

    sev = incident.get("severity", "LOW").upper()
    c.setFillColor(_severity_color(sev))
    c.rect(24 * mm, 205 * mm, 42 * mm, 12 * mm, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 12)
    c.drawCentredString(45 * mm, 209 * mm, sev)


def _draw_summary(c: canvas.Canvas, incident: dict):
    _draw_page_title(c, "Executive Summary")
    c.setFont("Helvetica", 11)
    summary = [
        f"Shadow-OT detected a {incident.get('severity', 'LOW')} anomaly for session {incident['session_id']}.",
        f"The SOAR pipeline progressed to {incident.get('playbook_state', 'CONTAINED')} and deployed containment controls without impacting production nodes.",
        f"Threat analysis mapped {len(incident.get('techniques', []))} ATT&CK techniques and preserved complete forensic artifacts.",
    ]
    y = 250 * mm
    for line in summary:
        c.drawString(24 * mm, y, line)
        y -= 8 * mm

    metrics = [
        ["Duration", incident.get("duration", "90s")],
        ["Commands Captured", str(incident.get("commands_captured", 0))],
        ["Techniques Detected", str(len(incident.get("techniques", [])))],
        ["ATT&CK Stage Reached", incident.get("attack_stage", "impact")],
        ["Real Nodes Compromised", "0"],
    ]
    table = Table(metrics, colWidths=[70 * mm, 90 * mm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F3F4F6")),
        ("BOX", (0, 0), (-1, -1), 1, colors.black),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#9CA3AF")),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
    ]))
    table.wrapOn(c, 0, 0)
    table.drawOn(c, 24 * mm, 150 * mm)


def _draw_timeline(c: canvas.Canvas, incident: dict):
    _draw_page_title(c, "Attack Timeline")
    entries = incident.get("timeline", [])
    x = 35 * mm
    c.setStrokeColor(colors.HexColor("#374151"))
    c.line(x, 40 * mm, x, 250 * mm)
    y = 245 * mm
    palette = {"attack": colors.red, "defense": colors.green, "trap": colors.orange}
    for item in entries[:8]:
        color = palette.get(item.get("kind", "attack"), colors.red)
        c.setFillColor(color)
        c.circle(x, y, 3.5 * mm, fill=1)
        c.setFillColor(colors.black)
        c.setFont("Helvetica", 10)
        c.drawString(45 * mm, y - 1 * mm, f"{item.get('time')} — {item.get('event')}")
        y -= 25 * mm


def _draw_profile(c: canvas.Canvas, incident: dict):
    _draw_page_title(c, "Attacker Profile")
    profile = incident.get("profile", {})
    scores = profile.get("behavioral_scores", {})
    y = 245 * mm
    for name, value in list(scores.items())[:5]:
        c.setFont("Helvetica", 10)
        c.drawString(24 * mm, y, name.replace("_", " ").title())
        c.setFillColor(colors.HexColor("#1D4ED8"))
        c.rect(70 * mm, y - 2 * mm, (value * 100) * 1.0 * mm, 4 * mm, fill=1, stroke=0)
        c.setFillColor(colors.black)
        y -= 12 * mm
    c.setFont("Helvetica-Bold", 12)
    c.drawString(24 * mm, 160 * mm, f"APT Match: {profile.get('apt_match', 'Unknown')} ({profile.get('confidence', 0)}%)")
    c.setFont("Helvetica", 11)
    top = profile.get("top_techniques", [])[:3]
    for i, t in enumerate(top, start=1):
        c.drawString(24 * mm, (150 - i * 8) * mm, f"{i}. {t}")


def _draw_attack_table(c: canvas.Canvas, incident: dict):
    _draw_page_title(c, "MITRE ATT&CK Techniques")
    rows = [["Technique ID", "Name", "Tactic", "Evidence", "Status"]]
    for t in incident.get("techniques", []):
        rows.append([t.get("id", ""), t.get("name", ""), ",".join(t.get("tactics", [])), t.get("evidence", "telemetry"), t.get("status", "confirmed")])
    table = Table(rows, colWidths=[26 * mm, 40 * mm, 36 * mm, 50 * mm, 25 * mm])
    style = [
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#9CA3AF")),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E5E7EB")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ]
    for i in range(1, len(rows)):
        style.append(("BACKGROUND", (0, i), (-1, i), colors.HexColor("#F9FAFB" if i % 2 == 0 else "#FFFFFF")))
    table.setStyle(TableStyle(style))
    table.wrapOn(c, 0, 0)
    table.drawOn(c, 12 * mm, 170 * mm)


def _draw_recommendations(c: canvas.Canvas, incident: dict):
    _draw_page_title(c, "Recommendations")
    recs = incident.get("recommendations", [])
    c.setFont("Helvetica", 11)
    y = 245 * mm
    for idx, rec in enumerate(recs[:5], start=1):
        c.drawString(24 * mm, y, f"{idx}. {rec}")
        y -= 12 * mm
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(24 * mm, 20 * mm, "Generated by Shadow-OT Automated Response Engine")


def generate_incident_report(incident: dict, output_dir: str):
    os.makedirs(output_dir, exist_ok=True)
    now = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    out_path = os.path.join(output_dir, f"incident_{incident['session_id']}_{now}.pdf")
    c = canvas.Canvas(out_path, pagesize=A4)

    _draw_cover(c, incident)
    c.showPage()
    _draw_summary(c, incident)
    c.showPage()
    _draw_timeline(c, incident)
    c.showPage()
    _draw_profile(c, incident)
    c.showPage()
    _draw_attack_table(c, incident)
    c.showPage()
    _draw_recommendations(c, incident)
    c.save()
    return out_path
